name: Buf Lint and Generate

on:
  pull_request:
  push:
    branches:
      - master

  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-setup-action@v1
        with:
          version: 1.0.0
      - uses: bufbuild/buf-lint-action@v1
      - run: buf generate server --template server/buf.gen.yaml
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Generated protobuf files"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
